//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace QuestionAnalisys.Racai {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="pdkTtlwsSoapBinding", Namespace="http://ws.racai.ro/pdk/ttlws")]
    public partial class TTL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SentenceSplitterOperationCompleted;
        
        private System.Threading.SendOrPostCallback TokenizerOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaggerOperationCompleted;
        
        private System.Threading.SendOrPostCallback LemmatizerOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChunkerOperationCompleted;
        
        private System.Threading.SendOrPostCallback XCESOperationCompleted;
        
        private System.Threading.SendOrPostCallback UTF8toSGMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback SGMLtoUTF8OperationCompleted;
        
        private System.Threading.SendOrPostCallback SGMLtoUTF7OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TTL() {
            this.Url = global::QuestionAnalisys.Properties.Settings.Default.QuestionAnalisys_Racai_TTL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SentenceSplitterCompletedEventHandler SentenceSplitterCompleted;
        
        /// <remarks/>
        public event TokenizerCompletedEventHandler TokenizerCompleted;
        
        /// <remarks/>
        public event TaggerCompletedEventHandler TaggerCompleted;
        
        /// <remarks/>
        public event LemmatizerCompletedEventHandler LemmatizerCompleted;
        
        /// <remarks/>
        public event ChunkerCompletedEventHandler ChunkerCompleted;
        
        /// <remarks/>
        public event XCESCompletedEventHandler XCESCompleted;
        
        /// <remarks/>
        public event UTF8toSGMLCompletedEventHandler UTF8toSGMLCompleted;
        
        /// <remarks/>
        public event SGMLtoUTF8CompletedEventHandler SGMLtoUTF8Completed;
        
        /// <remarks/>
        public event SGMLtoUTF7CompletedEventHandler SGMLtoUTF7Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#SentenceSplitter", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("SentenceSplitterReturn")]
        public string SentenceSplitter(string lang, string instr) {
            object[] results = this.Invoke("SentenceSplitter", new object[] {
                        lang,
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SentenceSplitterAsync(string lang, string instr) {
            this.SentenceSplitterAsync(lang, instr, null);
        }
        
        /// <remarks/>
        public void SentenceSplitterAsync(string lang, string instr, object userState) {
            if ((this.SentenceSplitterOperationCompleted == null)) {
                this.SentenceSplitterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSentenceSplitterOperationCompleted);
            }
            this.InvokeAsync("SentenceSplitter", new object[] {
                        lang,
                        instr}, this.SentenceSplitterOperationCompleted, userState);
        }
        
        private void OnSentenceSplitterOperationCompleted(object arg) {
            if ((this.SentenceSplitterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SentenceSplitterCompleted(this, new SentenceSplitterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#Tokenizer", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("TokenizerReturn")]
        public string Tokenizer(string lang, string instr) {
            object[] results = this.Invoke("Tokenizer", new object[] {
                        lang,
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TokenizerAsync(string lang, string instr) {
            this.TokenizerAsync(lang, instr, null);
        }
        
        /// <remarks/>
        public void TokenizerAsync(string lang, string instr, object userState) {
            if ((this.TokenizerOperationCompleted == null)) {
                this.TokenizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTokenizerOperationCompleted);
            }
            this.InvokeAsync("Tokenizer", new object[] {
                        lang,
                        instr}, this.TokenizerOperationCompleted, userState);
        }
        
        private void OnTokenizerOperationCompleted(object arg) {
            if ((this.TokenizerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TokenizerCompleted(this, new TokenizerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#Tagger", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("TaggerReturn")]
        public string Tagger(string lang, string instr) {
            object[] results = this.Invoke("Tagger", new object[] {
                        lang,
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TaggerAsync(string lang, string instr) {
            this.TaggerAsync(lang, instr, null);
        }
        
        /// <remarks/>
        public void TaggerAsync(string lang, string instr, object userState) {
            if ((this.TaggerOperationCompleted == null)) {
                this.TaggerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaggerOperationCompleted);
            }
            this.InvokeAsync("Tagger", new object[] {
                        lang,
                        instr}, this.TaggerOperationCompleted, userState);
        }
        
        private void OnTaggerOperationCompleted(object arg) {
            if ((this.TaggerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaggerCompleted(this, new TaggerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#Lemmatizer", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("LemmatizerReturn")]
        public string Lemmatizer(string lang, string instr) {
            object[] results = this.Invoke("Lemmatizer", new object[] {
                        lang,
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LemmatizerAsync(string lang, string instr) {
            this.LemmatizerAsync(lang, instr, null);
        }
        
        /// <remarks/>
        public void LemmatizerAsync(string lang, string instr, object userState) {
            if ((this.LemmatizerOperationCompleted == null)) {
                this.LemmatizerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLemmatizerOperationCompleted);
            }
            this.InvokeAsync("Lemmatizer", new object[] {
                        lang,
                        instr}, this.LemmatizerOperationCompleted, userState);
        }
        
        private void OnLemmatizerOperationCompleted(object arg) {
            if ((this.LemmatizerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LemmatizerCompleted(this, new LemmatizerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#Chunker", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("ChunkerReturn")]
        public string Chunker(string lang, string instr) {
            object[] results = this.Invoke("Chunker", new object[] {
                        lang,
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChunkerAsync(string lang, string instr) {
            this.ChunkerAsync(lang, instr, null);
        }
        
        /// <remarks/>
        public void ChunkerAsync(string lang, string instr, object userState) {
            if ((this.ChunkerOperationCompleted == null)) {
                this.ChunkerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChunkerOperationCompleted);
            }
            this.InvokeAsync("Chunker", new object[] {
                        lang,
                        instr}, this.ChunkerOperationCompleted, userState);
        }
        
        private void OnChunkerOperationCompleted(object arg) {
            if ((this.ChunkerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChunkerCompleted(this, new ChunkerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#XCES", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("XCESReturn")]
        public string XCES(string lang, string parid, string instr) {
            object[] results = this.Invoke("XCES", new object[] {
                        lang,
                        parid,
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XCESAsync(string lang, string parid, string instr) {
            this.XCESAsync(lang, parid, instr, null);
        }
        
        /// <remarks/>
        public void XCESAsync(string lang, string parid, string instr, object userState) {
            if ((this.XCESOperationCompleted == null)) {
                this.XCESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXCESOperationCompleted);
            }
            this.InvokeAsync("XCES", new object[] {
                        lang,
                        parid,
                        instr}, this.XCESOperationCompleted, userState);
        }
        
        private void OnXCESOperationCompleted(object arg) {
            if ((this.XCESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XCESCompleted(this, new XCESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#UTF8toSGML", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("UTF8toSGMLReturn")]
        public string UTF8toSGML(string instr) {
            object[] results = this.Invoke("UTF8toSGML", new object[] {
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UTF8toSGMLAsync(string instr) {
            this.UTF8toSGMLAsync(instr, null);
        }
        
        /// <remarks/>
        public void UTF8toSGMLAsync(string instr, object userState) {
            if ((this.UTF8toSGMLOperationCompleted == null)) {
                this.UTF8toSGMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUTF8toSGMLOperationCompleted);
            }
            this.InvokeAsync("UTF8toSGML", new object[] {
                        instr}, this.UTF8toSGMLOperationCompleted, userState);
        }
        
        private void OnUTF8toSGMLOperationCompleted(object arg) {
            if ((this.UTF8toSGMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UTF8toSGMLCompleted(this, new UTF8toSGMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#SGMLtoUTF8", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("SGMLtoUTF8Return")]
        public string SGMLtoUTF8(string instr) {
            object[] results = this.Invoke("SGMLtoUTF8", new object[] {
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SGMLtoUTF8Async(string instr) {
            this.SGMLtoUTF8Async(instr, null);
        }
        
        /// <remarks/>
        public void SGMLtoUTF8Async(string instr, object userState) {
            if ((this.SGMLtoUTF8OperationCompleted == null)) {
                this.SGMLtoUTF8OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSGMLtoUTF8OperationCompleted);
            }
            this.InvokeAsync("SGMLtoUTF8", new object[] {
                        instr}, this.SGMLtoUTF8OperationCompleted, userState);
        }
        
        private void OnSGMLtoUTF8OperationCompleted(object arg) {
            if ((this.SGMLtoUTF8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SGMLtoUTF8Completed(this, new SGMLtoUTF8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://ws.racai.ro/pdk/ttlws#SGMLtoUTF7", RequestNamespace="http://ws.racai.ro/pdk/ttlws", ResponseNamespace="http://ws.racai.ro/pdk/ttlws")]
        [return: System.Xml.Serialization.SoapElementAttribute("SGMLtoUTF7Return")]
        public string SGMLtoUTF7(string instr) {
            object[] results = this.Invoke("SGMLtoUTF7", new object[] {
                        instr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SGMLtoUTF7Async(string instr) {
            this.SGMLtoUTF7Async(instr, null);
        }
        
        /// <remarks/>
        public void SGMLtoUTF7Async(string instr, object userState) {
            if ((this.SGMLtoUTF7OperationCompleted == null)) {
                this.SGMLtoUTF7OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSGMLtoUTF7OperationCompleted);
            }
            this.InvokeAsync("SGMLtoUTF7", new object[] {
                        instr}, this.SGMLtoUTF7OperationCompleted, userState);
        }
        
        private void OnSGMLtoUTF7OperationCompleted(object arg) {
            if ((this.SGMLtoUTF7Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SGMLtoUTF7Completed(this, new SGMLtoUTF7CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SentenceSplitterCompletedEventHandler(object sender, SentenceSplitterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SentenceSplitterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SentenceSplitterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TokenizerCompletedEventHandler(object sender, TokenizerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TokenizerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TokenizerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TaggerCompletedEventHandler(object sender, TaggerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaggerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaggerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LemmatizerCompletedEventHandler(object sender, LemmatizerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LemmatizerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LemmatizerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ChunkerCompletedEventHandler(object sender, ChunkerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChunkerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChunkerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void XCESCompletedEventHandler(object sender, XCESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XCESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XCESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UTF8toSGMLCompletedEventHandler(object sender, UTF8toSGMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UTF8toSGMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UTF8toSGMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SGMLtoUTF8CompletedEventHandler(object sender, SGMLtoUTF8CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SGMLtoUTF8CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SGMLtoUTF8CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SGMLtoUTF7CompletedEventHandler(object sender, SGMLtoUTF7CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SGMLtoUTF7CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SGMLtoUTF7CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591