//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34011.
// 
#pragma warning disable 1591

namespace QuestionAnalisys.PosTaggerRoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PosTaggerRoWSPortBinding", Namespace="http://webPosRo.uaic/")]
    public partial class PosTaggerRoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback parseText_TXTOperationCompleted;
        
        private System.Threading.SendOrPostCallback parseSentence_TXTOperationCompleted;
        
        private System.Threading.SendOrPostCallback parseText_XMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback parseSentence_XMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PosTaggerRoWS() {
            this.Url = global::QuestionAnalisys.Properties.Settings.Default.QuestionAnalisys_PosTaggerRoWS_PosTaggerRoWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event parseText_TXTCompletedEventHandler parseText_TXTCompleted;
        
        /// <remarks/>
        public event parseSentence_TXTCompletedEventHandler parseSentence_TXTCompleted;
        
        /// <remarks/>
        public event parseText_XMLCompletedEventHandler parseText_XMLCompleted;
        
        /// <remarks/>
        public event parseSentence_XMLCompletedEventHandler parseSentence_XMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webPosRo.uaic/", ResponseNamespace="http://webPosRo.uaic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parseText_TXT([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rawTextInput) {
            object[] results = this.Invoke("parseText_TXT", new object[] {
                        rawTextInput});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void parseText_TXTAsync(string rawTextInput) {
            this.parseText_TXTAsync(rawTextInput, null);
        }
        
        /// <remarks/>
        public void parseText_TXTAsync(string rawTextInput, object userState) {
            if ((this.parseText_TXTOperationCompleted == null)) {
                this.parseText_TXTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparseText_TXTOperationCompleted);
            }
            this.InvokeAsync("parseText_TXT", new object[] {
                        rawTextInput}, this.parseText_TXTOperationCompleted, userState);
        }
        
        private void OnparseText_TXTOperationCompleted(object arg) {
            if ((this.parseText_TXTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parseText_TXTCompleted(this, new parseText_TXTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webPosRo.uaic/", ResponseNamespace="http://webPosRo.uaic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parseSentence_TXT([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rawSentenceInput) {
            object[] results = this.Invoke("parseSentence_TXT", new object[] {
                        rawSentenceInput});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void parseSentence_TXTAsync(string rawSentenceInput) {
            this.parseSentence_TXTAsync(rawSentenceInput, null);
        }
        
        /// <remarks/>
        public void parseSentence_TXTAsync(string rawSentenceInput, object userState) {
            if ((this.parseSentence_TXTOperationCompleted == null)) {
                this.parseSentence_TXTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparseSentence_TXTOperationCompleted);
            }
            this.InvokeAsync("parseSentence_TXT", new object[] {
                        rawSentenceInput}, this.parseSentence_TXTOperationCompleted, userState);
        }
        
        private void OnparseSentence_TXTOperationCompleted(object arg) {
            if ((this.parseSentence_TXTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parseSentence_TXTCompleted(this, new parseSentence_TXTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webPosRo.uaic/", ResponseNamespace="http://webPosRo.uaic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parseText_XML([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rawTextInput) {
            object[] results = this.Invoke("parseText_XML", new object[] {
                        rawTextInput});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void parseText_XMLAsync(string rawTextInput) {
            this.parseText_XMLAsync(rawTextInput, null);
        }
        
        /// <remarks/>
        public void parseText_XMLAsync(string rawTextInput, object userState) {
            if ((this.parseText_XMLOperationCompleted == null)) {
                this.parseText_XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparseText_XMLOperationCompleted);
            }
            this.InvokeAsync("parseText_XML", new object[] {
                        rawTextInput}, this.parseText_XMLOperationCompleted, userState);
        }
        
        private void OnparseText_XMLOperationCompleted(object arg) {
            if ((this.parseText_XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parseText_XMLCompleted(this, new parseText_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webPosRo.uaic/", ResponseNamespace="http://webPosRo.uaic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parseSentence_XML([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rawSentenceInput) {
            object[] results = this.Invoke("parseSentence_XML", new object[] {
                        rawSentenceInput});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void parseSentence_XMLAsync(string rawSentenceInput) {
            this.parseSentence_XMLAsync(rawSentenceInput, null);
        }
        
        /// <remarks/>
        public void parseSentence_XMLAsync(string rawSentenceInput, object userState) {
            if ((this.parseSentence_XMLOperationCompleted == null)) {
                this.parseSentence_XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparseSentence_XMLOperationCompleted);
            }
            this.InvokeAsync("parseSentence_XML", new object[] {
                        rawSentenceInput}, this.parseSentence_XMLOperationCompleted, userState);
        }
        
        private void OnparseSentence_XMLOperationCompleted(object arg) {
            if ((this.parseSentence_XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parseSentence_XMLCompleted(this, new parseSentence_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void parseText_TXTCompletedEventHandler(object sender, parseText_TXTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parseText_TXTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parseText_TXTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void parseSentence_TXTCompletedEventHandler(object sender, parseSentence_TXTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parseSentence_TXTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parseSentence_TXTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void parseText_XMLCompletedEventHandler(object sender, parseText_XMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parseText_XMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parseText_XMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void parseSentence_XMLCompletedEventHandler(object sender, parseSentence_XMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parseSentence_XMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parseSentence_XMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591