//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace QuestionAnalisys.NamedEntityRecognizerWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NamedEntityRecognizerWSPortBinding", Namespace="http://recognizer.entity.named.uaic/")]
    public partial class NamedEntityRecognizerWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback recognizeEntitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback recognizeEntities_XMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NamedEntityRecognizerWS() {
            this.Url = global::QuestionAnalisys.Properties.Settings.Default.QuestionAnalisys_NamedEntityRecognizerWS_NamedEntityRecognizerWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event recognizeEntitiesCompletedEventHandler recognizeEntitiesCompleted;
        
        /// <remarks/>
        public event recognizeEntities_XMLCompletedEventHandler recognizeEntities_XMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://recognizer.entity.named.uaic/", ResponseNamespace="http://recognizer.entity.named.uaic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recognizeEntities([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string text, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string language) {
            object[] results = this.Invoke("recognizeEntities", new object[] {
                        text,
                        language});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void recognizeEntitiesAsync(string text, string language) {
            this.recognizeEntitiesAsync(text, language, null);
        }
        
        /// <remarks/>
        public void recognizeEntitiesAsync(string text, string language, object userState) {
            if ((this.recognizeEntitiesOperationCompleted == null)) {
                this.recognizeEntitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecognizeEntitiesOperationCompleted);
            }
            this.InvokeAsync("recognizeEntities", new object[] {
                        text,
                        language}, this.recognizeEntitiesOperationCompleted, userState);
        }
        
        private void OnrecognizeEntitiesOperationCompleted(object arg) {
            if ((this.recognizeEntitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recognizeEntitiesCompleted(this, new recognizeEntitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://recognizer.entity.named.uaic/", ResponseNamespace="http://recognizer.entity.named.uaic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recognizeEntities_XML([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string language) {
            object[] results = this.Invoke("recognizeEntities_XML", new object[] {
                        xml,
                        language});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void recognizeEntities_XMLAsync(string xml, string language) {
            this.recognizeEntities_XMLAsync(xml, language, null);
        }
        
        /// <remarks/>
        public void recognizeEntities_XMLAsync(string xml, string language, object userState) {
            if ((this.recognizeEntities_XMLOperationCompleted == null)) {
                this.recognizeEntities_XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecognizeEntities_XMLOperationCompleted);
            }
            this.InvokeAsync("recognizeEntities_XML", new object[] {
                        xml,
                        language}, this.recognizeEntities_XMLOperationCompleted, userState);
        }
        
        private void OnrecognizeEntities_XMLOperationCompleted(object arg) {
            if ((this.recognizeEntities_XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recognizeEntities_XMLCompleted(this, new recognizeEntities_XMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void recognizeEntitiesCompletedEventHandler(object sender, recognizeEntitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recognizeEntitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recognizeEntitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void recognizeEntities_XMLCompletedEventHandler(object sender, recognizeEntities_XMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recognizeEntities_XMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recognizeEntities_XMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591