//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionAnalisys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nlptools.infoiasi.ro:80/WebNpChunkerRo/NpChunkerRoWS")]
        public string QuestionAnalisys_NpChunkerRoWS_NpChunkerRoWS {
            get {
                return ((string)(this["QuestionAnalisys_NpChunkerRoWS_NpChunkerRoWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nlptools.infoiasi.ro:80/WebPosRo/PosTaggerRoWS")]
        public string QuestionAnalisys_PosTaggerRoWS_PosTaggerRoWS {
            get {
                return ((string)(this["QuestionAnalisys_PosTaggerRoWS_PosTaggerRoWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nlptools.infoiasi.ro:80/UAIC.NamedEntityRecognizer/NamedEntityRecognizerWS" +
            "")]
        public string QuestionAnalisys_NamedEntityRecognizerWS_NamedEntityRecognizerWS {
            get {
                return ((string)(this["QuestionAnalisys_NamedEntityRecognizerWS_NamedEntityRecognizerWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nlptools.infoiasi.ro:80/UAIC.AnaphoraResolution/AnaphoraResolutionWS")]
        public string QuestionAnalisys_AnaphoraResolutionWS_AnaphoraResolutionWS {
            get {
                return ((string)(this["QuestionAnalisys_AnaphoraResolutionWS_AnaphoraResolutionWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nlptools.infoiasi.ro:80/UAIC.DiscourseParser/DiscourseParserWS")]
        public string QuestionAnalisys_DiscourseParserWS_DiscourseParserWS {
            get {
                return ((string)(this["QuestionAnalisys_DiscourseParserWS_DiscourseParserWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.racai.ro:8080/pdk/ttlws")]
        public string QuestionAnalisys_Racai_TTL {
            get {
                return ((string)(this["QuestionAnalisys_Racai_TTL"]));
            }
        }
    }
}
