
namespace APIs
{
   public  class Language
   {
       private Alchemy alchemyObj;
       private string Text;
       public string xml;
       public Language(string text)
       {
           Text = text;
           alchemyObj = new Alchemy();
          
          
       }

       public string GetLanguage()
       {
           xml = alchemyObj.TextGetLanguage(Text);
           return xml;
       }

       /*
          <?xml version="1.0" encoding="UTF-8" ?> 
- <results>
  <status>OK</status> 
  <usage>By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html</usage> 
  <url /> 
  <language>english</language> 
  <iso-639-1>en</iso-639-1> 
  <iso-639-2>eng</iso-639-2> 
  <iso-639-3>eng</iso-639-3> 
  <ethnologue>http://www.ethnologue.com/show_language.asp?code=eng</ethnologue> 
  <native-speakers>309-400 million</native-speakers> 
  <wikipedia>http://en.wikipedia.org/wiki/English_language</wikipedia> 
  </results>
  
  
  
    <?xml version="1.0" encoding="UTF-8" ?> 
- <results>
  <status>OK</status> 
  <usage>By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html</usage> 
  <url /> 
  <language>romanian</language> 
  <iso-639-1>ro</iso-639-1> 
  <iso-639-2>ron</iso-639-2> 
  <iso-639-3>ron</iso-639-3> 
  <ethnologue>http://www.ethnologue.com/show_language.asp?code=ron</ethnologue> 
  <native-speakers>24 million</native-speakers> 
  <wikipedia>http://en.wikipedia.org/wiki/Romanian_language</wikipedia> 
  </results>
        */
   }
}
